import json
import geopandas as gpd

def cleaning_data(path_tree_results: str):
    with open(path_tree_results) as json_file:
        data_tree_height = json.load(json_file)

    number_of_tiles = len(data_tree_height["features"])
    # for each tile get the features and conoctate them in a list
    tree_feature_list = []

    for i in range(number_of_tiles):
        try:
            features = data_tree_height["features"][i]["features"]["features"] # get each tree height feature list
            tree_feature_list = tree_feature_list + features  # combine all tree height features into one list
        except KeyError as e:
            pass

    # write tree height features into geojson file if you want to visualize file in GIS
    with open(f"treeheight_asturias.geojson", "w") as dst:
        collection = {
            "type": "FeatureCollection",
            "features": tree_feature_list
        }
        dst.write(json.dumps(collection))

    trees_gdf = gpd.read_file('treeheight_asturias.geojson')
    # kepler requires crs in lat/long thus transforming crs is require
    trees_gdf.set_crs(epsg=3857, inplace=True, allow_override=True)
    geo_trees_gdf = trees_gdf.to_crs(epsg=4326)

    # create separate dataframe with only tall trees (above 6m)
    high_trees_gdf = geo_trees_gdf.loc[(geo_trees_gdf['height'] >= 6)]

    return geo_trees_gdf, high_trees_gdf


def get_kepler_config():
 config = {'config': {'mapState': {'bearing': 12.732663821526033,
                         'dragRotate': True,
                         'isSplit': False,
                         'latitude': 43.56307771903234,
                         'longitude': -5.966771905350275,
                         'pitch': 54.847690688748024,
                         'zoom': 14.164356912639555},
            'mapStyle': {'mapStyles': {},
                         'styleType': 'satellite',
                         'threeDBuildingColor': [9.665468314072013,
                                                 17.18305478057247,
                                                 31.1442867897876],
                         'topLayerGroups': {},
                         'visibleLayerGroups': {}},
            'visState': {'animationConfig': {'currentTime': None, 'speed': 1},
                         'filters': [],
                         'interactionConfig': {'brush': {'enabled': False,
                                                         'size': 0.5},
                                               'coordinate': {'enabled': False},
                                               'geocoder': {'enabled': False},
                                               'tooltip': {'compareMode': False,
                                                           'compareType': 'absolute',
                                                           'enabled': True,
                                                           'fieldsToShow': {'all trees': [{'format': None,
                                                                                           'name': 'id'},
                                                                                          {'format': None,
                                                                                           'name': 'height'}],
                                                                            'high trees': [{'format': None,
                                                                                            'name': 'id'},
                                                                                           {'format': None,
                                                                                            'name': 'height'}],
                                                                            'train lines': []}}},
                         'layerBlending': 'normal',
                         'layers': [{'config': {'color': [227, 26, 26],
                                                'columns': {'geojson': 'geometry'},
                                                'dataId': 'high trees',
                                                'hidden': False,
                                                'isVisible': True,
                                                'label': 'high trees',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'elevationScale': 1,
                                                              'enable3d': True,
                                                              'filled': True,
                                                              'heightRange': [0,
                                                                              500],
                                                              'opacity': 0.8,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'sizeRange': [0,
                                                                            10],
                                                              'strokeColor': [255,
                                                                              203,
                                                                              153],
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'strokeOpacity': 0.8,
                                                              'stroked': False,
                                                              'thickness': 0.5,
                                                              'wireframe': False}},
                                     'id': 'rtsq8e',
                                     'type': 'geojson',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'heightField': {'name': 'height',
                                                                        'type': 'real'},
                                                        'heightScale': 'linear',
                                                        'radiusField': None,
                                                        'radiusScale': 'linear',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}},
                                    {'config': {'color': [182, 228, 144],
                                                'columns': {'geojson': 'geometry'},
                                                'dataId': 'all trees',
                                                'hidden': False,
                                                'isVisible': True,
                                                'label': 'all trees',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'elevationScale': 1,
                                                              'enable3d': True,
                                                              'filled': True,
                                                              'heightRange': [0,
                                                                              500],
                                                              'opacity': 0.8,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'sizeRange': [0,
                                                                            10],
                                                              'strokeColor': [130,
                                                                              154,
                                                                              227],
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'strokeOpacity': 0.8,
                                                              'stroked': True,
                                                              'thickness': 0.5,
                                                              'wireframe': False}},
                                     'id': 'svkcn82',
                                     'type': 'geojson',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'heightField': {'name': 'height',
                                                                        'type': 'real'},
                                                        'heightScale': 'linear',
                                                        'radiusField': None,
                                                        'radiusScale': 'linear',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}},
                                    {'config': {'color': [248, 149, 112],
                                                'columns': {'geojson': 'geometry'},
                                                'dataId': 'train lines',
                                                'hidden': False,
                                                'isVisible': True,
                                                'label': 'train lines',
                                                'textLabel': [{'alignment': 'center',
                                                               'anchor': 'start',
                                                               'color': [255,
                                                                         255,
                                                                         255],
                                                               'field': None,
                                                               'offset': [0, 0],
                                                               'size': 18}],
                                                'visConfig': {'colorRange': {'category': 'Uber',
                                                                             'colors': ['#5A1846',
                                                                                        '#900C3F',
                                                                                        '#C70039',
                                                                                        '#E3611C',
                                                                                        '#F1920E',
                                                                                        '#FFC300'],
                                                                             'name': 'Global '
                                                                                     'Warming',
                                                                             'type': 'sequential'},
                                                              'elevationScale': 5,
                                                              'enable3d': False,
                                                              'filled': False,
                                                              'heightRange': [0,
                                                                              500],
                                                              'opacity': 0.8,
                                                              'radius': 10,
                                                              'radiusRange': [0,
                                                                              50],
                                                              'sizeRange': [0,
                                                                            10],
                                                              'strokeColor': [184,
                                                                              110,
                                                                              218],
                                                              'strokeColorRange': {'category': 'Uber',
                                                                                   'colors': ['#5A1846',
                                                                                              '#900C3F',
                                                                                              '#C70039',
                                                                                              '#E3611C',
                                                                                              '#F1920E',
                                                                                              '#FFC300'],
                                                                                   'name': 'Global '
                                                                                           'Warming',
                                                                                   'type': 'sequential'},
                                                              'strokeOpacity': 0.8,
                                                              'stroked': True,
                                                              'thickness': 1.7,
                                                              'wireframe': False}},
                                     'id': 'h9l2b0h',
                                     'type': 'geojson',
                                     'visualChannels': {'colorField': None,
                                                        'colorScale': 'quantile',
                                                        'heightField': None,
                                                        'heightScale': 'linear',
                                                        'radiusField': None,
                                                        'radiusScale': 'linear',
                                                        'sizeField': None,
                                                        'sizeScale': 'linear',
                                                        'strokeColorField': None,
                                                        'strokeColorScale': 'quantile'}}],
                         'splitMaps': []}},
 'version': 'v1'}
 return config